### ISSUE TITLE
Collaboration?

### ISSUE THREAD

**Issue by saebekassebil** [danigb/achord#1]
Wow Dani, you're on fire!

It's incredible to see all the modules you're producing - great work!

I started a module like this a while ago, called [piu](https://github.com/saebekassebil/piu). It uses an entirely different strategy than yours, but maybe we could collaborate, sharing tests, etc.?

// Jakob

**Comment by saebekassebil** [comment]
Woops. Now I see that the purpose of this module is not the same as the other one. Not entirely anyway.

più is for inferring chords from just notes, while this is more of a "gluing" intervals together to form chords.

**Comment by danigb** [comment]
I really like the idea of più (and this is the ultimate objetive of achord -or a similar module in the future-). As you can see I'm in the process of building a lot of small modules with the long-term objective of build a complete js music library.  I'm open to any kind of collaboration :+1:
